In [4]:
import pandas as pd
import numpy as np

#Calling the csv data
df = pd.read_csv("montreal_transit_dataset.csv")

#Convert timestamp to a date object that Python can read
df['timestamp'] = pd.to_datetime(df['timestamp'])

df['hour_of_day'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek

print(df['is_delayed'].value_counts())

is_delayed
0    8007
Name: count, dtype: int64

In [37]:
import meteostat as ms
from datetime import datetime, timedelta

end_date = datetime.now() 
start_date = end_date - timedelta(days=10)

weather_df = ms.hourly(
    station='71627',
    start=start_date,
    end=end_date
).fetch().reset_index()
weather_df = weather_df.fillna(0)

print(weather_df.shape)
weather_df.head()

(240, 12)

,time,temp,rhum,prcp,snwd,wdir,wspd,wpgt,pres,tsun,cldc,coco
0,2026-05-31 04:00:00,13.1,60,0.0,0,280,9.0,31.5,0.0,0,6,2
1,2026-05-31 05:00:00,13.1,61,0.0,0,260,10.0,31.5,0.0,0,2,3
2,2026-05-31 06:00:00,13.3,59,0.0,0,260,13.0,31.5,0.0,0,4,3
3,2026-05-31 07:00:00,12.9,60,0.0,0,260,14.0,29.6,0.0,0,8,3
4,2026-05-31 08:00:00,12.1,69,0.0,0,250,11.0,25.9,0.0,0,2,3

In [40]:
import pandas as pd

transit_df = pd.read_csv('montreal_transit_history.csv')

transit_df['timestamp'] = pd.to_datetime(transit_df['timestamp'])
weather_df['time'] = pd.to_datetime(weather_df['time'])

transit_df['merge_hour'] = transit_df['timestamp'].dt.floor('h')

#merging
final_dataset = pd.merge(
    left=transit_df,
    right=weather_df,
    left_on='merge_hour',
    right_on='time',
    how='left'
)

final_dataset = final_dataset.drop(columns=['merge_hour','time'])

print(final_dataset.shape)
final_dataset.head()

(133990, 16)

,timestamp,route_id,delay_seconds,delay_minutes,is_delayed,temp,rhum,prcp,snwd,wdir,wspd,wpgt,pres,tsun,cldc,coco
0,2026-06-08 04:09:46,371,0,0.0,0,15.8,79,0.0,0,200,5.0,31.5,0.0,0,0,1
1,2026-06-08 04:09:46,371,0,0.0,0,15.8,79,0.0,0,200,5.0,31.5,0.0,0,0,1
2,2026-06-08 04:09:46,371,0,0.0,0,15.8,79,0.0,0,200,5.0,31.5,0.0,0,0,1
3,2026-06-08 04:09:46,371,0,0.0,0,15.8,79,0.0,0,200,5.0,31.5,0.0,0,0,1
4,2026-06-08 04:09:46,371,0,0.0,0,15.8,79,0.0,0,200,5.0,31.5,0.0,0,0,1